/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "zaze-server"

include("core:database")
include(":core:common")

include("feature:showcase")
include("core:model")
findProject(":core:model")?.name = "model"
include("feature:application")
findProject(":feature:application")?.name = "application"
