/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "zaze-server"

include(":core:database")
include(":core:common")
//include(":core:model")
include(":feature:showcase")
include(":feature:application")
include(":feature:ad")
