server:
  port: 8080
  servlet:
    # 应用路径，配置应用路径，可方便进行反向代理
    context-path: /
    session:
      timeout: 30m #默认（分钟）：30m


spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/dev?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#    type: com.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
## okHttp 配置
ok:
  http:
    connect-timeout: 60
    read-timeout: 60
    write-timeout: 60
    max-idle-connections: 200
    keep-alive-duration: 300
